resolver: lts-20.4
extra-deps:
  - amazonka-2.0
  - amazonka-core-2.0
  - amazonka-s3-2.0
  - amazonka-sso-2.0
  - amazonka-sts-2.0

  - amazonka-mtl-0.1.1.0

  # for amazonka-core-2.0
  - crypton-0.33
